[package]
name = "polygonify"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.13", features = ["derive"] }
dotenv = "0.15.0"
geo = "0.18.0"
maturin = "0.12.6"
num-traits = "0.2.14"
rand = "0.8.4"
serde_json = "1.0.78"